### ISSUE TITLE
Headings id

### ISSUE THREAD

**Issue by Skaant** [abstract-core/nebula-atoms#8]
Automatically set `h1`, `h2` and `h3`'s `id` attribute from text content.

## Rules

* Letters are converted to lowercase,
* Accents are replaced with their base letter,
* Convert spaces & apostrophes to `-`.

**Comment by Tim-jn** [comment]
.normalize("NFD") -> enlève les accents
    .split(" ") 
    .join("-") -> remplace les espaces par des tirets
    .replace(/[^a-z-]/g, "") -> enlève tous les caractères spéciaux sauf les tirets
    .replace(/^\-?|\-?$/g, "") -> supprime les tirets en première et dernière position

**Comment by Tim-jn** [comment]
Je pense qu'il y a moyen d'optimiser ça avec une regex plus poussée, j'ai trouvé le site https://www.autoregex.xyz/ qui est une IA qui génère des Regex, mais j'ai épuisé mes utilisations pour ce mois
